name: Build Python EXE

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller openpyxl
        pip install tkcalendar
        pip install xlwings
        pip install pywin32

    - name: Crear carpeta reportes
      run: mkdir reportes

    - name: Build EXE
      run: pyinstaller --onefile --windowed --name=procesador_excel_gui --hidden-import=openpyxl --hidden-import=tkinter --exclude-module=numpy codigo_local.py

    - name: Crear archivo LEEME
      run: echo "Este archivo fue generado automáticamente. Es seguro y no contiene malware." > dist\LEEME.txt

    - name: Comprimir EXE en ZIP
      run: powershell Compress-Archive -Path dist\procesador_excel_gui.exe,dist\LEEME.txt -DestinationPath dist\procesador_excel_gui.zip

    - name: Upload ZIP artifact
      uses: actions/upload-artifact@v4
      with:
        name: procesador_excel_gui
        path: dist/procesador_excel_gui.zip
