name: Build Optimized Python EXE with Nuitka

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nuitka openpyxl tkcalendar xlwings pywin32 ordered-set zstandard

    - name: Crear carpeta reportes
      run: mkdir reportes

    - name: Build EXE with Nuitka (Optimizado)
      run: |
        python -m nuitka `
          --standalone `
          --onefile `
          --windows-disable-console `
          --output-dir=dist `
          --output-filename=procesador_excel_gui.exe `
          --enable-plugin=tk-inter `
          --include-package=openpyxl `
          --include-package=xlwings `
          --include-package=pywin32 `
          --include-data-dir=reportes=reportes `
          --remove-output `
          --assume-yes-for-downloads `
          codigo_python.py

    - name: Crear archivo LEEME
      run: echo "Este archivo fue generado automáticamente con Nuitka. Es seguro y no contiene malware." > dist\LEEME.txt

    - name: Comprimir EXE en ZIP
      run: powershell Compress-Archive -Path dist\procesador_excel_gui.exe,dist\LEEME.txt -DestinationPath dist\procesador_excel_gui.zip

    - name: Upload ZIP artifact
      uses: actions/upload-artifact@v4
      with:
        name: procesador_excel_gui_nuitka_optimized
        path: dist/procesador_excel_gui.zip
        retention-days: 1
